// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoutubeResearchMcp.Data;

#nullable disable

namespace YoutubeResearchMcp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503202448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("YoutubeResearchMcp.Data.Entities.ModelWeights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BiasesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("biases_json");

                    b.Property<int>("EpochsTrained")
                        .HasColumnType("INTEGER")
                        .HasColumnName("epochs_trained");

                    b.Property<double>("FinalLoss")
                        .HasColumnType("REAL")
                        .HasColumnName("final_loss");

                    b.Property<string>("Niche")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("niche");

                    b.Property<string>("NormMeanJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("norm_mean_json");

                    b.Property<string>("NormStddevJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("norm_stddev_json");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("trained_at");

                    b.Property<int>("VideosUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("videos_used");

                    b.Property<string>("WeightsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("weights_json");

                    b.HasKey("Id");

                    b.HasIndex("Niche");

                    b.HasIndex("TrainedAt");

                    b.ToTable("model_weights");
                });

            modelBuilder.Entity("YoutubeResearchMcp.Data.Entities.VideoRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_title");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("collected_at");

                    b.Property<long>("CommentCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comment_count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("duration");

                    b.Property<long>("LikeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("like_count");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("niche");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<string>("TagsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("video_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt");

                    b.HasIndex("Niche");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("video_records");
                });
#pragma warning restore 612, 618
        }
    }
}
